SET SQLBLANKLINES ON

CREATE TABLE APP_ORDER (
    ID         NUMBER(19)   NOT NULL,
    PRODUCT_ID NUMBER(19)   NOT NULL,
    QUANTITY   NUMBER(10)   NOT NULL,
    STATUS     VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_APP_ORDER PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_APP_ORDER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE INVENTORY (
    ID              NUMBER(19) NOT NULL,
    PRODUCT_ID      NUMBER(19) NOT NULL,
    AVAILABLE_STOCK NUMBER(10) NOT NULL,

    CONSTRAINT PK_INVENTORY PRIMARY KEY (ID),
    CONSTRAINT UK_INVENTORY_PRODUCT UNIQUE (PRODUCT_ID)
);

CREATE SEQUENCE SEQ_INVENTORY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;